name: Docker Image CI

on:
  push:
    branches: [ orani-v3.3.0-bounds-release ]
  pull_request:
    branches: [ orani-v3.3.0-bounds-release ]

jobs:
  docker-build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
    
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: oraniadmin/mastodon
          tags: orani-v3.3.0-bounds-hidepost-test